# Build Stage
FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY src /app/src
COPY pom.xml /app/
RUN mvn clean package

# Run Stage
FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY --from=builder /app/${JAR_FILE} /client-service.jar
ENTRYPOINT ["java", "-jar", "/gateway-service.jar"]
